### ISSUE TITLE
Any plans for a Drupal 8 version of the module

### ISSUE THREAD

**Issue by frederickjh** [duosecurity/duo_drupal#2]
Hi!
Drupal 8 has been out now for over a year and half. Does Duo Security have any plans for a Drupal 8 version of the module?

Thanks!
Frederick

**Comment by mschwager** [comment]
Hey @frederickjh! In fact we have been considering adding Drupal 8 support! There's currently no timeline in place, but we'll let you know as soon as that changes :)

**Comment by manuel-work** [comment]
I have done the work here, and built a plugin for the [tfa](https://www.drupal.org/project/tfa) module that integrates Duo for Drupal 8.

I was about to create the project page, but it turns out that there is already a [tfa_duo](https://www.drupal.org/project/tfa_duo) module on drupal.org. However since it is only available for D7 I have attached mine and a request to become the maintainer for that branch here:

https://www.drupal.org/project/tfa_duo/issues/2929090  (module is attached as a zip file there).

**Comment by DuoKristina** [comment]
Hi @manuel-appnovation. I'm sure the Drupal community appreciates your efforts. 

The "tfa_duo" project you linked may appear official, but it isn't actually our supported Drupal project, and wasn't created by Duo's Engineering group. The only Drupal project we created and support is [duo](https://www.drupal.org/project/duo).

To protect the integrity of our open-source projects, we do not permit maintainers from outside the Duo Security organization.

**Comment by manuel-work** [comment]
@DuoKristina thanks for the kind words. I was just informing people in this issue and others that might end up on it that there is something out there.

I was not offering to maintain https://github.com/duosecurity/duo_drupal, and I don’t believe this issue should be closed, unless you are never going to port this project to Drupal 8.

**Comment by frederickjh** [comment]
@DuoKristina  Not sure how this new information warrants  the closing this issue. Has Duo release a duo module for Drupal 8 that I don't know about?

That would warrant closing this issue or Duo deciding that the are not going to create a Drupal 8 version of the module, but either way you should state why you closed the issue.

**Comment by DuoKristina** [comment]
@frederickjh Good point! At this time we still don't have any near-future plan to support Drupal 8.

**Comment by frederickjh** [comment]
Just wanted to point out for anyone finding this issue that even though Duo has no near-future plans to support Drupal 8, there is a community built alternative for Drupal 8, [Two Factor Authentication for Duo Security](https://www.drupal.org/project/tfa_duo). 

Both this module and the [Two-factor Authentication (TFA)](https://www.drupal.org/project/tfa) module that it requires currently have alpha versions available on [drupal.org](https://drupal.org).

**Comment by wimleers** [comment]
Another year has passed. Silence here and on the sibling issue on drupal.org: https://www.drupal.org/project/duo/issues/2904475.

**Comment by boyangz** [comment]
@wimleers Sorry I don't have better news, but unfortunately at this time we still don't have any near-future plans to support Drupal 8. I would also encourage you submit feature requests so that our product team can properly assess desire for this feature and prioritize it accordingly.

**Comment by DuoKristina** [comment]
Duo has ended support for our Drupal 6/7 module as of Jan 28, 2021, and will not develop a Drupal 8 module.
